### ISSUE TITLE
Make access levels more user friendly

### ISSUE THREAD

**Issue by maebeam** [bitclout/identity#11]
The current icons and descriptions cause confusion for users.

cc @lobovkin

**Comment by iPaulPro** [comment]
> The main thing is to show only what the third-party service requests. Don't show what it doesn't request.

I'm not sure I agree since it's important to be clear that higher level permissions include the implicit permissions of the lower levels.

---

I'd argue we shouldn't strive to contain the levels to single sentences. I'm not great with copy, but perhaps something like:

**Access my basic information**
Includes public key, BTC deposit address, and any other public information.

**Post, like, and follow**
[domain] may edit my profile, create posts and reclouts, follow and unfollow accounts, and send messages on my behalf.

**Unrestricted access**
[domain] may buy, sell, or send coins without explicit approval.

**Comment by maebeam** [comment]
Fixed!
