### ISSUE TITLE
Can't decrypt messages: Bad private key

### ISSUE THREAD

**Issue by andrewarrow** [bitclout/identity#44]
Any idea how to help this user?

![debug2](https://user-images.githubusercontent.com/127054/123016569-c9825000-d37f-11eb-91dd-fdb9b8ae0cdc.png)

**Comment by Onurklngc** [comment]
I have the same problem on my account, only the printed traceback is a little different.
![image](https://user-images.githubusercontent.com/22586149/125195189-4c9b1580-e25d-11eb-8f9b-8ad3e3a1c7a7.png)

After debugging in the browser, I saw that it is due to the transformation of the private key to the buffer([here](https://github.com/bitclout/identity/blob/281ee335ac6989fab43562117855829e3ff6aac5/src/app/signing.service.ts#L67)), since the private key buffer array is created with a length of 31 instead of 32 based on its element values on some accounts. I was able to view the received messages after predefining array length. Created a [PR](https://github.com/bitclout/identity/pull/52).
